// Vila Abandonada - Game Map Data
// Generated by Location Editor

const GAME_MAP = {
    "floresta": {
        "id": "floresta",
        "name": "Floresta",
        "description": "Descrição do local...",
        "image": "images/floresta.jpg",
        "unlocked": true,
        "connections": [
            "portao_entrada"
        ],
        "hotspots": [
            {
                "id": "hotspot_1761880449282",
                "name": "Portão",
                "action": "navigate",
                "target": "portao_entrada",
                "position": {
                    "x": 34.85714285714286,
                    "y": 51.65714285714286,
                    "width": 32.457142857142856,
                    "height": 17.142857142857142
                },
                "arrowDirection": "up"
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "portao_entrada": {
        "id": "portao_entrada",
        "name": "Portao de entrada",
        "description": "Descrição do local...",
        "image": "images/portao_entrada.jpg",
        "unlocked": false,
        "connections": [
            "rua_vila",
            "floresta",
            "florest"
        ],
        "hotspots": [
            {
                "id": "hotspot_1761881974352",
                "name": "Portão Aberto",
                "action": "navigate",
                "target": "rua_vila",
                "position": {
                    "x": 26.171428571428574,
                    "y": 51.42857142857142,
                    "width": 50.74285714285715,
                    "height": 34.05714285714286
                },
                "arrowDirection": "up"
            },
            {
                "id": "hotspot_1761882044866",
                "name": "Voltar",
                "action": "navigate",
                "target": "floresta",
                "position": {
                    "x": 1.7142857142857144,
                    "y": 94.17142857142858,
                    "width": 98.28571428571429,
                    "height": 5.599999999999994
                },
                "arrowDirection": "down",
                "zoomDirection": "out"
            }
        ],
        "items": [
            {
                "id": "mapa",
                "name": "mapa",
                "found": false,
                "size": {
                    "width": 80,
                    "height": 80
                },
                "position": {
                    "x": 12.2857,
                    "y": 88.4
                },
                "transform": {
                    "rotation": 0,
                    "scaleX": 1,
                    "scaleY": 1,
                    "flipX": false,
                    "flipY": false,
                    "rotateX": -39,
                    "rotateY": 0,
                    "skewX": 0,
                    "skewY": 0,
                    "opacity": 0.6,
                    "shadowBlur": 0,
                    "shadowOffsetX": 0,
                    "shadowOffsetY": 0
                },
                "image": "images/items/mapa_antigo.png"
            }
        ],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "rua_vila": {
        "id": "rua_vila",
        "name": "Rua da Vila",
        "description": "Descrição do local...",
        "image": "images/rua_vila.jpg",
        "unlocked": false,
        "connections": [
            "portao_entrada",
            "praca_central",
            "casa_abandonada_01_frente",
            "casa_abandonada_02_frente",
            "portao_entrada_fechado"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762217336538",
                "name": "voltar",
                "action": "navigate",
                "target": "portao_entrada_fechado",
                "position": {
                    "x": 2.6285714285714286,
                    "y": 90.51428571428572,
                    "width": 97.14285714285714,
                    "height": 8.571428571428571
                }
            },
            {
                "id": "hotspot_1762217400265",
                "name": "Praça Central",
                "action": "navigate",
                "target": "praca_central",
                "position": {
                    "x": 38.628571428571426,
                    "y": 51.42857142857142,
                    "width": 22.857142857142858,
                    "height": 12
                }
            },
            {
                "id": "hotspot_1762217435547",
                "name": "Casa Abandonada...",
                "action": "navigate",
                "target": "casa_abandonada_02_frente",
                "position": {
                    "x": 63.65714285714286,
                    "y": 50.4,
                    "width": 9.6,
                    "height": 12.457142857142857
                }
            },
            {
                "id": "hotspot_1762217467877",
                "name": "Casa Abandonada...",
                "action": "navigate",
                "target": "casa_abandonada_01_frente",
                "position": {
                    "x": 5.828571428571429,
                    "y": 45.94285714285714,
                    "width": 20.228571428571428,
                    "height": 20.914285714285715
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "praca_central": {
        "id": "praca_central",
        "name": "Praça Central",
        "description": "Descrição do local...",
        "image": "images/praca_central.jpg",
        "unlocked": false,
        "connections": [
            "rua_vila",
            "poco_profundo",
            "rua_final"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762218868135",
                "name": "voltar",
                "action": "navigate",
                "target": "rua_vila",
                "position": {
                    "x": 1.9428571428571426,
                    "y": 90.85714285714286,
                    "width": 96.34285714285714,
                    "height": 8.914285714285715
                }
            },
            {
                "id": "hotspot_1762218884462",
                "name": "Poço",
                "action": "navigate",
                "target": "poco_profundo",
                "position": {
                    "x": 34.4,
                    "y": 58.51428571428572,
                    "width": 32.228571428571435,
                    "height": 19.428571428571416
                }
            },
            {
                "id": "hotspot_1762218927341",
                "name": "Rua",
                "action": "navigate",
                "target": "rua_final",
                "position": {
                    "x": 39.08571428571428,
                    "y": 47.31428571428572,
                    "width": 22.742857142857144,
                    "height": 8.228571428571428
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "poco_profundo": {
        "id": "poco_profundo",
        "name": "Poço Profundo",
        "description": "Descrição do local...",
        "image": "images/poco_profundo.jpg",
        "unlocked": false,
        "connections": [
            "praca_central"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762220160331",
                "name": "voltar",
                "action": "navigate",
                "target": "praca_central",
                "position": {
                    "x": 8.114285714285714,
                    "y": 83.65714285714286,
                    "width": 87.77142857142857,
                    "height": 16.114285714285714
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_01_frente": {
        "id": "casa_abandonada_01_frente",
        "name": "Casa Abandonada",
        "description": "Uma Casa Abandonada",
        "image": "images/casa_abandonada_01_frente.jpg",
        "unlocked": false,
        "connections": [
            "rua_vila",
            "casa_abandonada_01_porta_entrada"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762217986271",
                "name": "voltar",
                "action": "navigate",
                "target": "rua_vila",
                "position": {
                    "x": 3.7714285714285714,
                    "y": 94.97142857142858,
                    "width": 92.22857142857143,
                    "height": 4
                }
            },
            {
                "id": "hotspot_1762219620288",
                "name": "Porta",
                "action": "navigate",
                "target": "casa_abandonada_01_porta_entrada",
                "position": {
                    "x": 38.857142857142854,
                    "y": 59.65714285714285,
                    "width": 23.65714285714286,
                    "height": 20.457142857142856
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_01_sala": {
        "id": "casa_abandonada_01_sala",
        "name": "casa_abandonada_01_sala",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_01_sala.jpg",
        "unlocked": false,
        "connections": [
            "casa_abandonada_01_porta_entrada",
            "casa_abandonada_01_quarto"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219678577",
                "name": "saida",
                "action": "navigate",
                "target": "casa_abandonada_01_porta_entrada",
                "position": {
                    "x": 22.857142857142858,
                    "y": 37.82857142857143,
                    "width": 17.257142857142856,
                    "height": 31.428571428571438
                }
            },
            {
                "id": "hotspot_1762219709454",
                "name": "Quarto",
                "action": "navigate",
                "target": "casa_abandonada_01_quarto",
                "position": {
                    "x": 82.85714285714286,
                    "y": 50.05714285714286,
                    "width": 16.457142857142856,
                    "height": 32.57142857142858
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_01_quarto": {
        "id": "casa_abandonada_01_quarto",
        "name": "casa_abandonada_01_quarto",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_01_quarto.jpg",
        "unlocked": false,
        "connections": [
            "casa_abandonada_01_sala"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219732963",
                "name": "voltar",
                "action": "navigate",
                "target": "casa_abandonada_01_sala",
                "position": {
                    "x": 4.685714285714285,
                    "y": 91.65714285714286,
                    "width": 90.17142857142856,
                    "height": 7.885714285714286
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_02_frente": {
        "id": "casa_abandonada_02_frente",
        "name": "casa_abandonada_02_frente",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_02_frente.jpg",
        "unlocked": false,
        "connections": [
            "rua_vila",
            "casa_abandonada_01_porta_entrada",
            "casa_abandonada_02_porta_entrada"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762218005832",
                "name": "voltar",
                "action": "navigate",
                "target": "rua_vila",
                "position": {
                    "x": 1.6,
                    "y": 93.60000000000001,
                    "width": 96.91428571428573,
                    "height": 5.828571428571429
                }
            },
            {
                "id": "hotspot_1762219822282",
                "name": "Porta",
                "action": "navigate",
                "target": "casa_abandonada_02_porta_entrada",
                "position": {
                    "x": 41.94285714285714,
                    "y": 50.28571428571429,
                    "width": 14.514285714285712,
                    "height": 28.685714285714287
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_02_quintal": {
        "id": "casa_abandonada_02_quintal",
        "name": "casa_abandonada_02_quintal",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_02_quintal.jpg",
        "unlocked": false,
        "connections": [
            "casa_abandonada_02_cozinha"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219981419",
                "name": "cozinha",
                "action": "navigate",
                "target": "casa_abandonada_02_cozinha",
                "position": {
                    "x": 2.857142857142857,
                    "y": 92.80000000000001,
                    "width": 88.68571428571428,
                    "height": 4.8
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "portao_entrada_fechado": {
        "id": "portao_entrada_fechado",
        "name": "Portão de Entrada",
        "description": "Descrição do local...",
        "image": "images/portao_entrada_fechado.jpg",
        "unlocked": false,
        "connections": [
            "rua_vila"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219540371",
                "name": "voltar",
                "action": "navigate",
                "target": "rua_vila",
                "position": {
                    "x": 4,
                    "y": 93.48571428571428,
                    "width": 87.2,
                    "height": 5.485714285714286
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_01_porta_entrada": {
        "id": "casa_abandonada_01_porta_entrada",
        "name": "casa_abandonada_01_porta_entrada",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_01_porta_entrada.jpg",
        "unlocked": false,
        "connections": [
            "casa_abandonada_01_frente",
            "casa_abandonada_01_sala",
            "casa_abandonada_02_frente",
            "a"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219649846",
                "name": "Porta",
                "action": "navigate",
                "target": "casa_abandonada_01_sala",
                "position": {
                    "x": 40.57142857142857,
                    "y": 34.85714285714286,
                    "width": 18.857142857142858,
                    "height": 34.51428571428571
                }
            },
            {
                "id": "hotspot_1762220062443",
                "name": "Voltar",
                "action": "navigate",
                "target": "casa_abandonada_01_frente",
                "position": {
                    "x": 0.9142857142857144,
                    "y": 90.4,
                    "width": 96.91428571428573,
                    "height": 6.2857142857142865
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_02_porta_entrada": {
        "id": "casa_abandonada_02_porta_entrada",
        "name": "casa_abandonada_02_porta_entrada",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_02_porta_entrada.jpg",
        "unlocked": false,
        "connections": [
            "casa_abandonada_02_sala",
            "casa_abandonada_02_frente"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219841625",
                "name": "Porta",
                "action": "navigate",
                "target": "casa_abandonada_02_sala",
                "position": {
                    "x": 28.45714285714286,
                    "y": 19.885714285714286,
                    "width": 28.685714285714287,
                    "height": 64.11428571428571
                }
            },
            {
                "id": "hotspot_1762219862162",
                "name": "Voltar",
                "action": "navigate",
                "target": "casa_abandonada_02_frente",
                "position": {
                    "x": 2.5142857142857142,
                    "y": 93.25714285714287,
                    "width": 92.68571428571428,
                    "height": 5.942857142857143
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_02_sala": {
        "id": "casa_abandonada_02_sala",
        "name": "casa_abandonada_02_sala",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_02_sala.jpg",
        "unlocked": false,
        "connections": [
            "casa_abandonada_02_porta_entrada",
            "casa_abandonada_02_cozinha"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219884306",
                "name": "Voltar",
                "action": "navigate",
                "target": "casa_abandonada_02_porta_entrada",
                "position": {
                    "x": 14.514285714285712,
                    "y": 88.8,
                    "width": 72.8,
                    "height": 10.057142857142857
                }
            },
            {
                "id": "hotspot_1762219906387",
                "name": "cozinha",
                "action": "navigate",
                "target": "casa_abandonada_02_cozinha",
                "position": {
                    "x": 41.714285714285715,
                    "y": 29.828571428571426,
                    "width": 17.257142857142856,
                    "height": 39.08571428571428
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "casa_abandonada_02_cozinha": {
        "id": "casa_abandonada_02_cozinha",
        "name": "casa_abandonada_02_cozinha",
        "description": "Descrição do local...",
        "image": "images/casa_abandonada_02_cozinha.jpg",
        "unlocked": false,
        "connections": [
            "casa_abandonada_02_sala",
            "casa_abandonada_02_quintal"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219940649",
                "name": "quintal",
                "action": "navigate",
                "target": "casa_abandonada_02_quintal",
                "position": {
                    "x": 42.628571428571426,
                    "y": 36.68571428571429,
                    "width": 14.399999999999999,
                    "height": 33.82857142857143
                }
            },
            {
                "id": "hotspot_1762219959550",
                "name": "voltar",
                "action": "navigate",
                "target": "casa_abandonada_02_sala",
                "position": {
                    "x": 11.085714285714285,
                    "y": 93.60000000000001,
                    "width": 77.82857142857142,
                    "height": 5.0285714285714285
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "rua_final": {
        "id": "rua_final",
        "name": "rua_final",
        "description": "Descrição do local...",
        "image": "images/rua_final.jpg",
        "unlocked": false,
        "connections": [
            "praca_central",
            "portao_saida",
            "cemiterio_entrada",
            "igreja_frente",
            "portao_saida_aberto",
            "portao_saida_cadeado",
            "igreja",
            "cemiterio_frente"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762218973475",
                "name": "Igreja",
                "action": "navigate",
                "target": "igreja_frente",
                "position": {
                    "x": 68.57142857142857,
                    "y": 38.628571428571426,
                    "width": 21.82857142857143,
                    "height": 23.314285714285717
                }
            },
            {
                "id": "hotspot_1762219016163",
                "name": "Cemiterio",
                "action": "navigate",
                "target": "cemiterio_entrada",
                "position": {
                    "x": 29.485714285714288,
                    "y": 46.62857142857143,
                    "width": 12.342857142857143,
                    "height": 15.2
                }
            },
            {
                "id": "hotspot_1762219056233",
                "name": "portao de saida",
                "action": "navigate",
                "target": "portao_saida",
                "position": {
                    "x": 42.857142857142854,
                    "y": 44.114285714285714,
                    "width": 15.085714285714285,
                    "height": 16.57142857142857
                }
            },
            {
                "id": "hotspot_1762220606704",
                "name": "Voltar",
                "action": "navigate",
                "target": "praca_central",
                "position": {
                    "x": 2.9714285714285715,
                    "y": 93.02857142857142,
                    "width": 91.2,
                    "height": 6.514285714285714
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "portao_saida": {
        "id": "portao_saida",
        "name": "portao_saida",
        "description": "Descrição do local...",
        "image": "images/portao_saida.jpg",
        "unlocked": false,
        "connections": [
            "rua_final",
            "portao_saida_cadeado"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219086592",
                "name": "voltar",
                "action": "navigate",
                "target": "rua_final",
                "position": {
                    "x": 1.4857142857142858,
                    "y": 94.74285714285713,
                    "width": 97.14285714285714,
                    "height": 4.8
                }
            },
            {
                "id": "hotspot_1762219443547",
                "name": "Cadeado",
                "action": "navigate",
                "target": "portao_saida_cadeado",
                "position": {
                    "x": 39.54285714285714,
                    "y": 51.31428571428571,
                    "width": 21.714285714285715,
                    "height": 19.885714285714286
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "portao_saida_aberto": {
        "id": "portao_saida_aberto",
        "name": "portao_saida_aberto",
        "description": "Descrição do local...",
        "image": "images/portao_saida_aberto.jpg",
        "unlocked": false,
        "connections": [
            "rua_final"
        ],
        "hotspots": [],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "cemiterio_entrada": {
        "id": "cemiterio_entrada",
        "name": "cemiterio_entrada",
        "description": "Descrição do local...",
        "image": "images/cemiterio_entrada.jpg",
        "unlocked": false,
        "connections": [
            "rua_final",
            "cemiterio_dentro"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219108004",
                "name": "voltar",
                "action": "navigate",
                "target": "rua_final",
                "position": {
                    "x": 4.457142857142857,
                    "y": 92.34285714285714,
                    "width": 91.2,
                    "height": 5.371428571428572
                }
            },
            {
                "id": "hotspot_1762219151983",
                "name": "Portao",
                "action": "navigate",
                "target": "cemiterio_dentro",
                "position": {
                    "x": 36.91428571428572,
                    "y": 50.05714285714286,
                    "width": 28.342857142857135,
                    "height": 35.42857142857142
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "cemiterio_dentro": {
        "id": "cemiterio_dentro",
        "name": "cemiterio_dentro",
        "description": "Descrição do local...",
        "image": "images/cemiterio_dentro.jpg",
        "unlocked": false,
        "connections": [
            "cemiterio_entrada",
            "cemiterio_mausoleo_frente",
            "cemiterio_musoleo_frente"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219192678",
                "name": "mausoleo",
                "action": "navigate",
                "target": "cemiterio_musoleo_frente",
                "position": {
                    "x": 43.65714285714286,
                    "y": 56.114285714285714,
                    "width": 12.685714285714287,
                    "height": 10.057142857142857
                }
            },
            {
                "id": "hotspot_1762219205848",
                "name": "voltar",
                "action": "navigate",
                "target": "cemiterio_entrada",
                "position": {
                    "x": 4,
                    "y": 93.60000000000001,
                    "width": 89.82857142857142,
                    "height": 4.228571428571429
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "cemiterio_mausoleo_frente": {
        "id": "cemiterio_mausoleo_frente",
        "name": "cemiterio_mausoleo_frente",
        "description": "Descrição do local...",
        "image": "images/cemiterio_mausoleo_frente.jpg",
        "unlocked": false,
        "connections": [
            "cemiterio_dentro",
            "cemiterio_mausoleo_dentro"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219236514",
                "name": "voltar",
                "action": "navigate",
                "target": "cemiterio_dentro",
                "position": {
                    "x": 2.2857142857142856,
                    "y": 93.02857142857142,
                    "width": 93.82857142857142,
                    "height": 6.2857142857142865
                }
            },
            {
                "id": "hotspot_1762219264688",
                "name": "Mausoleo",
                "action": "navigate",
                "target": "cemiterio_mausoleo_dentro",
                "position": {
                    "x": 42.51428571428571,
                    "y": 48.34285714285714,
                    "width": 15.314285714285713,
                    "height": 25.6
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "cemiterio_mausoleo_dentro": {
        "id": "cemiterio_mausoleo_dentro",
        "name": "cemiterio_mausoleo_dentro",
        "description": "Descrição do local...",
        "image": "images/cemiterio_mausoleo_dentro.jpg",
        "unlocked": false,
        "connections": [
            "cemiterio_mausoleo_frente"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219291926",
                "name": "voltar",
                "action": "navigate",
                "target": "cemiterio_mausoleo_frente",
                "position": {
                    "x": 7.657142857142857,
                    "y": 96.68571428571428,
                    "width": 86.74285714285715,
                    "height": 2.6285714285714286
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "portao_saida_cadeado": {
        "id": "portao_saida_cadeado",
        "name": "portao_saida_cadeado",
        "description": "Descrição do local...",
        "image": "images/portao_saida_cadeado.jpg",
        "unlocked": false,
        "connections": [
            "rua_final",
            "portao_saida_cadeado",
            "portao_saida"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219482728",
                "name": "voltar",
                "action": "navigate",
                "target": "portao_saida",
                "position": {
                    "x": 3.7714285714285714,
                    "y": 90.4,
                    "width": 89.25714285714285,
                    "height": 8.571428571428571
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "igreja_frente": {
        "id": "igreja_frente",
        "name": "igreja_frente",
        "description": "Descrição do local...",
        "image": "images/igreja_frente.jpg",
        "unlocked": false,
        "connections": [
            "rua_final",
            "igreja_dentro",
            "igreja_fundos"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219334081",
                "name": "fundos",
                "action": "navigate",
                "target": "igreja_fundos",
                "position": {
                    "x": 79.54285714285714,
                    "y": 57.714285714285715,
                    "width": 13.600000000000001,
                    "height": 14.971428571428572
                }
            },
            {
                "id": "hotspot_1762219341371",
                "name": "fundos",
                "action": "navigate",
                "target": "igreja_fundos",
                "position": {
                    "x": 4.3428571428571425,
                    "y": 54.85714285714286,
                    "width": 16,
                    "height": 16.685714285714287
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "igreja_dentro": {
        "id": "igreja_dentro",
        "name": "igreja_dentro",
        "description": "Descrição do local...",
        "image": "images/igreja_dentro.jpg",
        "unlocked": false,
        "connections": [
            "igreja_frente",
            "igreja_sinos"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219376485",
                "name": "voltar",
                "action": "navigate",
                "target": "igreja_frente",
                "position": {
                    "x": 2.742857142857143,
                    "y": 95.19999999999999,
                    "width": 94.74285714285713,
                    "height": 3.5428571428571427
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "igreja_fundos": {
        "id": "igreja_fundos",
        "name": "igreja_fundos",
        "description": "Descrição do local...",
        "image": "images/igreja_fundos.jpg",
        "unlocked": false,
        "connections": [
            "igreja_frente",
            "igreja_sinos"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219358148",
                "name": "voltar",
                "action": "navigate",
                "target": "igreja_frente",
                "position": {
                    "x": 1.9428571428571426,
                    "y": 94.17142857142858,
                    "width": 97.94285714285714,
                    "height": 4.571428571428571
                }
            },
            {
                "id": "hotspot_1762219400104",
                "name": "sinos",
                "action": "navigate",
                "target": "igreja_sinos",
                "position": {
                    "x": 38.857142857142854,
                    "y": 72.45714285714286,
                    "width": 10.057142857142857,
                    "height": 14.399999999999999
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    },
    "igreja_sinos": {
        "id": "igreja_sinos",
        "name": "igreja_sinos",
        "description": "Descrição do local...",
        "image": "images/igreja_sinos.jpg",
        "unlocked": false,
        "connections": [
            "igreja_dentro",
            "igreja_fundos"
        ],
        "hotspots": [
            {
                "id": "hotspot_1762219415589",
                "name": "voltar",
                "action": "navigate",
                "target": "igreja_fundos",
                "position": {
                    "x": 10.4,
                    "y": 90.74285714285715,
                    "width": 81.14285714285714,
                    "height": 7.542857142857143
                }
            }
        ],
        "items": [],
        "imageDimensions": {
            "width": 1024,
            "height": 1024
        }
    }
};

// Helper functions
function getLocation(locationId) {
    return GAME_MAP[locationId];
}

function getUnlockedLocations() {
    return Object.values(GAME_MAP).filter(loc => loc.unlocked);
}

// Export for use in game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { GAME_MAP, getLocation, getUnlockedLocations };
}
